dataset:
  dataroot: "/media/xukuan/0000678400004823/dataset/ground_texture/uniform/debug"
  camera_config: "/media/xukuan/0000678400004823/dataset/ground_texture/uniform/debug/camera.yaml"

correlation_flow:
  width: 448
  height: 448
  rotation_divisor: 720 # Higher means more accurate, but slower
  sigma: 0.2 # For Gaussian Kernel
  lambda: 0.1 # For regularization

map:
  grid_scale: 0.1 # the true size of one grid

loop_closure:
  position_response_thr: 140
  angle_response_thr: 10
  frame_gap_thr: 100
  distance_thr: 5  # in normalized plane
