dataset:
  dataroot: "/data/datasets/ground_texture/debug"
  camera_config: "/data/datasets/ground_texture/debug/camera.yaml"

correlation_flow:
  width: 448
  height: 448
  rotation_divisor: 720 # Higher means higher resolution, but slower
  rotation_channel: 448 # Lower means faster. Too lower, e.g., less than 10, may produce error about 1/rotation_divisor*360 degrees. 64 may work well.
  sigma: 0.2 # For Gaussian Kernel
  lambda: 0.1 # For regularization

keyframe_selection:
  min_distance: 0.2  # in normalized plane, real size equal min_distance*camera_height
  max_distance: 0.5  # in normalized plane, real size equal max_distance*camera_height
  min_angle: 6.3  # rad
  min_position_response: 80
  min_angle_response: 80

map:
  grid_scale: 0.1 # the true size of one grid

loop_closure:
  position_response_thr: 60 # this should be tuned together with width and height: higher width*height -> higher threshold
  angle_response_thr: 60 # this should be tuned together with rotation_divisor and rotation_channel: higher divisor*channel -> higher threshold
  frame_gap_thr: 100
  distance_thr: 5  # in normalized plane, real size equal distance_thr*camera_height
